config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { sessions: 'users/sessions', :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session_path
  end

  root "activities#index"

  resources :users, shallow: true do
    resources :activities do
      resources :attendances
      resources :ratings
    end
  end

  resources :locations

  resources :categories

  get 'activity/filter' => 'activity#filter'

  get 'activity/map' => 'activities#location'

  get 'activities/confirmation' => 'activities#confirmation'

  post 'activities/confirmation' => 'activities#confirmation'

end

app/models/activity.rb
  class Activity < ActiveRecord::Base
  belongs_to :user
  has_many :attendances
  has_many :ratings
  has_many :attendees, through: :attendances, source: :user
  before_create :check_params

  validates_numericality_of :participants, greater_than_or_equal_to: 1, message: "must be greater than 0"
  validates_numericality_of :active_participants, greater_than_or_equal_to: 0
  validates_inclusion_of :category, in: ['Sports', 'Culture', 'Coding', 'Education', 'Music', 'Comedy', 'Nightlife', 'Food', 'Outdoor', 'Other'], message: "Must choose category"
  validates_presence_of :location, :participants, :category, :tag, :title
  validates_presence_of :datetime, on: :create
  validate :date_cannot_be_in_past

  # geocoded_by :location
  # after_validation :geocode

  def has_spaces?
    self.active_participants < self.participants
  end

  def check_params
    self.tag.downcase!
  end


  def date_cannot_be_in_past
    errors.add(:datetime, "Your activity cannot be in the past! Leave the past where it is...") if
      !datetime.blank? and datetime < Date.today
  end

  def build_rating(params, user)
    rating = ratings.build(value: params[:value], user_id: user.id)
  end

  def has_happened?
    self.datetime < DateTime.now
  end

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  def index
    @tag = params["Tag"]
    if @tag
      @activities = Activity.where(tag: @tag.downcase)
    elsif params["Category"]
      @activities = Activity.where(category: params["Category"])
    else
      @activities = Activity.where(['datetime >= ?', DateTime.now]).order(datetime: :asc)
    end
    @categories = Category.pluck(:name)
  end

  def new
    @user = current_user
    @activity = Activity.new
    @categories = Category.pluck(:name)
  end

  def create
    @activity = current_user.activities.new(activity_params)
    @user = current_user
    if @activity.save
      flash[:notice] = "Your activity has been posted! Good luck!"
      ConfirmationMailer.confirm_activity(@activity, current_user).deliver_now
    else
      flash[:notice] = @activity.errors.full_messages.to_sentence
    end
    redirect_to root_path
  end

  def show
    @activity = Activity.find(params[:id])
    @attendance = @activity.attendances.where(user_id: current_user.id).where(activity_id: @activity.id)[0]
    @people_needed = @activity.participants - @activity.active_participants
    @geojson = Array.new
    @geojson << {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [@activity.longitude, @activity.latitude]
      },
      properties: {
        :'marker-color' => '#FE5F55',
        :'marker-symbol' => 'circle',
        :'marker-size' => 'medium'
        }
    }
    respond_to do |format|
      format.html
      format.json { render json: @geojson }
    end
  end

  def activity_params
    params.require(:activity).permit(:title, :description, :location, :participants, :datetime, :category, :tag, :latitude, :longitude)
  end

  def confirmation
    @user = current_user
    @activity = current_user.activities.new(activity_params)
    @categories = Category.pluck(:name)
  end

  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy
    redirect_to user_path(current_user)
  end
end

app/helpers/activity_helper.rb
module ActivityHelper
end

app/views/activities/confirmation.html.haml
%meta{:content => "initial-scale=1,maximum-scale=1,user-scalable=no", :name => "viewport"}/
%script{:src => "https://api.mapbox.com/mapbox.js/v2.2.2/mapbox.js"}
%link{:href => "https://api.mapbox.com/mapbox.js/v2.2.2/mapbox.css", :rel => "stylesheet"}/
%script{:src => "https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.min.js"}
%link{:href => "https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.mapbox.css", :rel => "stylesheet"}/
%link{:href => "https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/css/font-awesome.min.css", :rel => "stylesheet"}/
%script{:src => "/src/confirm_map.js"}

%section.create-activity.col-md-6.col-md-offset-3.col-xs-12.container.well
  %h2
    .confirm-head Confirm your activity
  %h4
    .confirm-head Check that the details below are correct then go down to the map
  %p
  = form_for [@user, @activity], :url => user_activities_path(@user), html: { multipart: true } do |f|
    %span.confirm-label Title:
    %span.form-group.form-input= f.text_field :title, :readonly => true, class: 'confirm-box'
    %p
    %span.confirm-label Description:
    %span.form-group.form-input= f.text_field :description, :readonly => true, class: 'confirm-box'
    %p
    %span.confirm-label People Needed:
    %span.form-group.form-input= f.text_field :participants,  { min: 1, :readonly => true, class: 'confirm-box' }
    %p
    %span.confirm-label When it's on:
    %span.form-group= f.text_field :datetime, { value: "#{@activity.datetime.strftime("%a %d %b, %Y - at %I:%M %p")}", :readonly => true, class: 'confirm-box' }
    %p
    %span.confirm-label Category:
    %span.form-group= f.text_field :category, :readonly => true, class: 'confirm-box'
    %p
    %span.confirm-label Tag:
    %span.form-group.form-input= f.text_field :tag, :readonly => true, class: 'confirm-box'
    %p
    %span.confirm-label Location:
    %span.form-group.form-input= f.text_field :location, :readonly => true, class: 'confirm-box'
    = f.hidden_field :latitude
    = f.hidden_field :longitude
    %p
    %div.form-group= f.submit "Confirm", class: "submit-btn"
  %h4
    .confirm-head Use the map to narrow down the perfect spot!
  #confirm_map{:style => "width:200" "height:350px"}
    .sk-folding-cube
      .sk-cube1.sk-cube
      .sk-cube2.sk-cube
      .sk-cube4.sk-cube
      .sk-cube3.sk-cube

app/views/activities/index.html.haml
#wrapper
  .hero.hidden-xs
    .hero-header
      %h1 Are you in?
      %section.activity-admin
        = form_tag categories_path, class: "col-xs-12", method: :get do
          = select_tag "Category", options_for_select(["Select category"] + @categories, :selected => params[:category]), :onchange => "this.form.submit()", class: "category-box", placeholder: "Select an option"
          %noscript= submit_tag "Filter", class: "filter_button"
        = form_tag root_path, class: "search_form", method: :get do
          = text_field_tag "Tag", nil, :placeholder => "Search for a pirate activity", class: "input-box"
          %noscript= submit_tag "Search", class: "search_button"
          %div.button-container.col-xs-12
            =link_to "Map view", locations_path, class: "btn map-button"
          - if current_user
            %div.button-container.col-xs-12
              =link_to "Add an activity", new_user_activity_path(current_user), class: "btn add-activity add-activity-large"

  .mobile.hidden-md.hidden-lg.hidden-sm
    %section.mobile-header.hidden-sm.hidden-md.hidden-lg
      %h1 Are you in?
      %section.mobile-activity-admin
        = form_tag root_path, class: "search_form", method: :get do
          = text_field_tag "Tag", nil, :placeholder => "Search for activity", class: "input-box"
          %noscript= submit_tag "Go", class: "search_button"
          %div.button-container.col-xs-12
            =link_to "Map view", locations_path, class: "btn map-button"
          - if current_user
            %div.button-container.col-xs-12
              =link_to "Add activity", new_user_activity_path(current_user), class: "btn add-activity"


  %section.latest.hidden-xs
    %h2.heading.heading--light.heading--center.heading--dark.section-header__title
      Latest Events
    .row
      .image-wrapper.col-md-4.col-sm-6
        =image_tag 'culture1.jpg'
        .text-box
          %h2 A cultural excursion
          %p Let's get our culture on :)
      .image-wrapper.col-md-4.col-sm-6
        =image_tag 'concert.jpg'
        .text-box
          %h2 Let's see a concert
          %p Wooohooooo
      .image-wrapper.col-md-4.col-sm-6
        =image_tag 'food2.jpg'
        .text-box
          %h2 Food market!
          %p Want to try some food?
      / %div.latest-activity.col-md-4.col-sm-6
      /   %img.act-image{:alt => "Mountain View", :src => "http://weknowyourdreams.com/images/football/football-08.jpg", :style => "width:320px;height:228px;"}/
      /   .event-overlay
      /     %h2 Event 1
      / %div.latest-activity.col-md-4.col-sm-6
      /   %img.act-image{:alt => "Mountain View", :src => "http://img2.10bestmedia.com/Images/Photos/284863/Create-Nightclub-3_54_990x660.jpg", :style => "width:320px;height:228px;"}/
      /   .event-overlay
      /     %h2 Event 2
      / %div.latest-activity.col-md-4.col-sm-6
      /   %img.act-image{:alt => "Mountain View", :src => "http://img2.10bestmedia.com/Images/Photos/284863/Create-Nightclub-3_54_990x660.jpg", :style => "width:320px;height:228px;"}/
      /   .event-overlay
      /     %h2 Event 3


  %section.categories.hidden-md.hidden-lg.hidden-sm
    .col-xs-6.no-padding
      =image_tag 'football-match.jpg', class: 'img-responsive'
      %div.overlay
        %a{:href => "/categories?utf8=✓&Category=Sports"} Sports
    .col-xs-6.no-padding
      =image_tag 'musicsmall.jpg', class: 'img-responsive'
      %div.overlay
        %a{:href => "/categories?utf8=✓&Category=Music"} Music
    .col-xs-6.no-padding
      =image_tag 'flowers.jpg', class: 'img-responsive'
      %div.overlay
        %a{:href => "/categories?utf8=✓&Category=Culture"} Culture
    .col-xs-6.no-padding
      =image_tag 'edu.jpg', class: 'img-responsive'
      %div.overlay
        %a{:href => "/categories?utf8=✓&Category=Education"} Education
    .col-xs-6.no-padding
      =image_tag 'code.jpg', class: 'img-responsive'
      %div.overlay
        %a{:href => "/categories?utf8=✓&Category=Coding"} Coding
    .col-xs-6.no-padding
      =image_tag 'night.jpg', class: 'img-responsive'
      %div.overlay
        %a{:href => "/categories?utf8=✓&Category=Nightlife"} Nightlife
    .col-xs-6.no-padding
      =image_tag 'monty.jpg', class: 'img-responsive'
      %div.overlay
        %a{:href => "/categories?utf8=✓&Category=Comedy"} Comedy
    .col-xs-6.no-padding
      =image_tag 'food5.jpg', class: 'img-responsive'
      %div.overlay
        %a{:href => "/categories?utf8=✓&Category=Food"} Food
    .col-xs-6.no-padding
      =image_tag 'outdoors.jpg', class: 'img-responsive'
      %div.overlay
        %a{:href => "/categories?utf8=✓&Category=Outdoors"} Outdoors
    .col-xs-6.no-padding
      =image_tag 'pirate.jpg', class: 'img-responsive'
      %div.overlay
        %a{:href => "/categories?utf8=✓&Category=Other"} Other

  %section#about-us
    %h2.heading.heading--light.heading--center.heading--dark.promoted-collection__title
      About Us
    .row
      .image-wrapper.col-md-2.col-sm-6.col-md-offset-1
        =image_tag 'retesh.JPG'
        .text-box
          %h2 Retesh Bajaj
          %p Spring onion
      .image-wrapper.col-md-2.col-sm-6
        =image_tag 'sarah.jpg'
        .text-box
          %h2 Sarah Middleton
          %p Apple
      .image-wrapper.col-md-2.col-sm-6
        =image_tag 'owen.JPG'
        .text-box
          %h2 Owen Lamb
          %p Leek
      .image-wrapper.col-md-2.col-sm-6
        =image_tag 'katya.JPG'
        .text-box
          %h2 Katya-yani Vyas
          %p Aubergine
      .image-wrapper.col-md-2.col-sm-6
        =image_tag 'fadi.jpg'
        .text-box
          %h2 Fadi Hakim
          %p Turnip

app/views/activities/new.html.erb
<div class='col-lg-6 col-lg-offset-3 container center'>
<% if @activity.errors.any? %>
  <section id="errors">
    <h2>
      <%= pluralize @activity.errors.count, "error" %>
      prohibited this activity from being saved:
    </h2>
    <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
  </section>
<% end %>
<%= form_for [@user, @activity], html: { multipart: true } do |f| %>
  <h1 class="text-center"> Create your Activity </h1>
    <form class="form-horizontal">
      <div class='row'><div class='form-group'><%= f.text_field :title,class: "col-sm-6 col-sm-offset-3", :placeholder => "Activity Name" %></div></div>
      <div class='row'><div class='form-group'><%= f.text_field :description,class: "col-sm-6 col-sm-offset-3", :placeholder => "Describe your Activity" %></div></div>
      <div class='row'><div class='form-group'><%= f.text_field :location,class: "col-sm-6 col-sm-offset-3", :placeholder => "Location" %></div></div>
      <div class='row'><div class='form-group'><%= f.number_field :participants,class: "col-sm-6 col-sm-offset-3", :placeholder => "People needed" %></div></div>
      <div class='row'><div class='form-group'><%= f.date_field :date,class: "col-sm-6 col-sm-offset-3", :placeholder => "Date" %></div></div>
      <div class='row'><div class='form-group'><%= f.time_field :time,class: "col-sm-6 col-sm-offset-3", :placeholder => "Time" %></div></div>
      <div class='row'><div class='form-group'><%= f.label :category %></div></div>
      <div class='row'><div class='form-group'><%= f.select :category,['Select', 'Sports', 'Culture', 'Coding', 'Education', 'Music', 'Comedy', 'Nightlife'] %></div></div>
      <div class='row'><div class='form-group'><%= f.text_field :tag,class: "col-sm-6 col-sm-offset-3", :placeholder => "Activity e.g.'Football'" %></div></div>
      <div class='row'><div class='form-group'><%= f.submit "Let's do it!", class: "btn btn-lg btn-primary" %></div></div>
    </form>
<% end %>
</div>
<!-- <%= form_for [@user, @activity], html: { multipart: true } do |f| %>
  <h1 class="text-center"> Create your Activity </h1>
    <ul class='col-md-offset-4 col-md-4 well list-unstyled text-center'>
      <li><div class='form-group'><%= f.text_field :title, :placeholder => "Activity Name" %></div> </li>
      <li><div class='form-group'><%= f.text_field :description, :placeholder => "Describe your Activity" %></div></li>
      <li><div class='form-group'><%= f.text_field :location, :placeholder => "Location" %></div></li>
      <li><div class='form-group'><%= f.number_field :participants, :placeholder => "People needed" %></div></li>
      <li><div class='form-group'><%= f.date_field :date, :placeholder => "Date" %></div></li>
      <li><div class='form-group'><%= f.time_field :time, :placeholder => "Time" %></div></li>
      <li><div class='form-group'><%= f.label :category %></div></li>
      <li><div class='form-group'><%= f.select :category, ['Select', 'Sports', 'Culture', 'Coding', 'Education', 'Music', 'Comedy', 'Nightlife'] %></div></li>
      <li><div class='form-group'><%= f.text_field :tag, :placeholder => "Activity e.g.'Football'" %></div></li>
      <li><div class='form-group'><%= f.submit "Let's do it!" %></div></li>
    </ul>
<% end %> -->

app/views/activities/new.html.haml
- if @activity.errors.any?
  %section#errors
    %h2
      = pluralize @activity.errors.count, "error"
      prohibited this activity from being saved:
    %ul
      - @activity.errors.full_messages.each do |message|
        %li= message

%section.create-activity.col-md-6.col-md-offset-3.col-xs-12container.center.well
  <h2>Add an activity!</h2>
  = form_for [@user, @activity], :url => activities_confirmation_path, html: { multipart: true } do |f|
    %div.form-group.form-input= f.text_field :title, {:required => true, :placeholder => "Activity Name" }
    %div.form-group.form-input= f.text_field :description, {:required => true, :placeholder => "Describe your Activity" }
    %div.form-group.form-input= f.text_field :location, {:required => true,  :placeholder => "Location" }
    %div.form-group.form-input= f.number_field :participants, {min: 1, :required => true,  :placeholder => "People needed"}
    = f.label :datetime
    %div.form-group= f.datetime_select :datetime
    = f.label :category
    %div.form-group= f.select :category,['Select', 'Sports', 'Culture', 'Coding', 'Education', 'Music', 'Comedy', 'Nightlife', 'Outdoor', 'Food', 'Other']
    %div.form-group.form-input= f.text_field :tag, {:required => true,  :placeholder => "Activity e.g.'Football'"}
    %div.form-group= f.submit "Let's do it!", class: "submit-btn"

app/views/activities/show.html.haml
%meta{:content => "initial-scale=1,maximum-scale=1,user-scalable=no", :name => "viewport"}/
%script{:src => "https://api.mapbox.com/mapbox.js/v2.2.2/mapbox.js"}
%link{:href => "https://api.mapbox.com/mapbox.js/v2.2.2/mapbox.css", :rel => "stylesheet"}/
%script{:src => "https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.min.js"}
%link{:href => "https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.mapbox.css", :rel => "stylesheet"}/
%link{:href => "https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/css/font-awesome.min.css", :rel => "stylesheet"}/
%link{:href => "https://fonts.googleapis.com/css?family=Lato|PT+Sans|Montserrat|Poiret+One", :rel => "stylesheet", :type => "text/css"}/
%script{:src => "/src/activity_map.js"}

%section.container
  .row
    %section.activity-info.col-md-8
      %ul.list-unstyled.act-list
        %li
          %h2= @activity.title
        %li
          %h3
            Hosted by:
            %span= link_to @activity.user.name, user_path(@activity.user)
        %li
          %b Details:
          %span= @activity.description
        %li
          %b Address:
          %span= @activity.location
        %li
          %b People still needed:
          %span.people_needed= @people_needed
        %li
          %b Capacity for this event: #{@activity.participants}
        %li
          %b When its on:
          %span= @activity.datetime.strftime("%a %d %b, %Y - at %I:%M %p")
        %li
          %b Category:
          = @activity.category


      - if @people_needed > 0 && !current_user.has_clicked?(@activity) && !current_user.activities.include?(@activity) && !@activity.has_happened?
        %p= link_to "I'm in!", activity_attendances_path(@activity), class: 'join_button'
      - elsif current_user.has_clicked?(@activity) && !@activity.has_happened?
        %p= link_to "I'm out!", attendance_path(@attendance), class: 'leave_button', method: :delete

      - if @activity.attendees.include?(current_user) && !current_user.rated_activites.include?(@activity)&& @activity.datetime < (Time.now)
        %p= link_to "Rate activity", new_activity_rating_path(@activity)

      - if !@activity.has_happened?
        %p= "You can rate this only after the event!"
      -elsif @activity.has_happened?
        %b Activity Rating:
        %span= "★" * @activity.ratings.average(:value).to_i + "☆" * (5 - @activity.ratings.average(:value).to_i)

      - if @activity.user == current_user && !@activity.has_happened?
        %p
        %p.delete=link_to "Delete activity", activity_path(@activity), method: :delete, class: "delete-btn"

    %section.activity-map#activity_map.col-md-4